// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfSfdoecp5xhrCLD2lF-FuLoNn0lBjB8Y',
    appId: '1:580482874005:web:1ebf3c4e52fe8cf1bd399c',
    messagingSenderId: '580482874005',
    projectId: 'meditationid',
    authDomain: 'meditationid.firebaseapp.com',
    storageBucket: 'meditationid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9IplAVHAAXEDind2L_MiULCgLLfH7KCs',
    appId: '1:580482874005:android:c4264344a5da5b25bd399c',
    messagingSenderId: '580482874005',
    projectId: 'meditationid',
    storageBucket: 'meditationid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvGjxYZ8rcd_mJhAPsfoDXGQXL49IQGoY',
    appId: '1:580482874005:ios:fa9c3cde965ffcf8bd399c',
    messagingSenderId: '580482874005',
    projectId: 'meditationid',
    storageBucket: 'meditationid.appspot.com',
    iosClientId: '580482874005-ivnuqgka2ckcpbhmqc2hg52cep4g31u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvGjxYZ8rcd_mJhAPsfoDXGQXL49IQGoY',
    appId: '1:580482874005:ios:fa9c3cde965ffcf8bd399c',
    messagingSenderId: '580482874005',
    projectId: 'meditationid',
    storageBucket: 'meditationid.appspot.com',
    iosClientId: '580482874005-ivnuqgka2ckcpbhmqc2hg52cep4g31u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditation',
  );
}
